version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: yarn install
            - run:
                name: Run unit tests with coverage
                command: yarn unitTest --coverage
workflows:
    build-and-test:
      jobs:
        - build-and-test
