version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            # - restore_cache:
            #     keys: 
            #       - aws-study-{{ .Branch }}-{{ checksum "yarn.lock" }}
            #       - aws-study-{{ .Branch }}-
            #       - aws-study-master
            #       - aws-study-
            - run:
                name: Install serverless
                command: sudo npm install -g serverless
            - run:
                name: Install dependencies
                command: yarn install
            # - save_cache:
            #     name: Save Yarn Package Cache
            #     key: aws-study-{{ .Branch }}-{{ checksum "yarn.lock" }}
            #     paths:
            #       - node_modules/
            - run:
                name: Run static code analysis
                command: yarn staticAnalysis:js
            - run:
                name: Run unit tests with coverage
                command: yarn unitTest:js --coverage
            - run:
                name: Run e2e start serverless offline
                background: true
                command: yarn e2eStart:local
            - run:
                name: Wating for serverless offline started 
                command: sleep 15
            - run:
                name: Run e2e test local for js
                command: yarn e2eTest:local:js
            - run:
                name: Run e2e test local for ts
                command: yarn e2eTest:local:ts
workflows:
    build-and-test:
      jobs:
        - build-and-test
